In [18]:
%load_ext autoreload
%autoreload 2
%reset -f

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [19]:
from pathlib import Path
import os
from os.path import join
import sys

# Find KPIHub root (directory containing lib/tables), then import lib.* as a package.
_here = Path.cwd().resolve()
_root = next((p for p in [_here, *list(_here.parents)[:12]] if (p / "lib" / "tables").is_dir()), None)
if _root is None:
    raise FileNotFoundError(
        f"Could not find KPIHub root (folder containing lib/tables). cwd={Path.cwd()!r}"
    )
sys.path.insert(0, str(_root))
os.chdir(_root)

from locallib.picarrodb import *
from locallib.slack import *
from locallib.etl import Loggers
from locallib.pandas import *

from lib.tables.IngesterTables import *
from lib.handlers.CustomerHandler import *
from lib.kpi_processor.KPIReport import *
from lib.config import *
from lib.KPIHubConnection import *
from lib.query.bank import *

from datetime import date
from datetime import timedelta

In [21]:
KPI_POR = KPIPOR('Cadent')
KPI_POR.query_table()
KPI_POR.process_data()
KPI_POR.push_data()

In [23]:
customer_list = get_customer_list(KPIHub_Conn)
customer_id = customer_list.iloc[0]['CustomerId']

In [29]:
Query(query = f"SELECT * FROM KPI_Data").execute(KPIHub_Conn)

,Id,KPIId,CustomerId,BoundaryRegion,Year,PeriodType,PeriodValue,Value,DataType,LastUpdated
0,FOVMain_Cadent_Y2023_W14,FOVMain,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2023,Weekly,14,None,None,2026-07-06 14:26:22.674023
1,FOVMain_Cadent_Y2023_W15,FOVMain,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2023,Weekly,15,None,None,2026-07-06 14:26:22.674023
2,FOVMain_Cadent_Y2023_W16,FOVMain,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2023,Weekly,16,None,None,2026-07-06 14:26:22.674023
3,FOVMain_Cadent_Y2023_W17,FOVMain,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2023,Weekly,17,None,None,2026-07-06 14:26:22.674023
4,FOVMain_Cadent_Y2023_W19,FOVMain,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2023,Weekly,19,None,None,2026-07-06 14:26:22.674023
...,...,...,...,...,...,...,...,...,...,...
31315,POR_Cadent_Y2026_W24,POR,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2026,Week,24,66.0,None,2026-07-08 18:42:58.447521
31316,POR_Cadent_Y2026_W25,POR,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2026,Week,25,68.0,None,2026-07-08 18:42:58.447521
31317,POR_Cadent_Y2026_W26,POR,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2026,Week,26,70.0,None,2026-07-08 18:42:58.447521
31318,POR_Cadent_Y2026_W27,POR,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2026,Week,27,73.0,None,2026-07-08 18:42:58.447521
31319,POR_Cadent_Y2026_W28,POR,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2026,Week,28,74.0,None,2026-07-08 18:42:58.447521

In [30]:
Query(query = f"SELECT * FROM KPI_Data WHERE CustomerId = '{customer_id}' AND KPIId = 'POR'").execute(KPIHub_Conn)

,Id,KPIId,CustomerId,BoundaryRegion,Year,PeriodType,PeriodValue,Value,DataType,LastUpdated
0,POR_Cadent_Y2023_W14,POR,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2023,Week,14,None,None,2026-07-08 18:42:58.447521
1,POR_Cadent_Y2023_W15,POR,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2023,Week,15,None,None,2026-07-08 18:42:58.447521
2,POR_Cadent_Y2023_W16,POR,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2023,Week,16,None,None,2026-07-08 18:42:58.447521
3,POR_Cadent_Y2023_W17,POR,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2023,Week,17,None,None,2026-07-08 18:42:58.447521
4,POR_Cadent_Y2023_W19,POR,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2023,Week,19,None,None,2026-07-08 18:42:58.447521
...,...,...,...,...,...,...,...,...,...,...
164,POR_Cadent_Y2026_W24,POR,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2026,Week,24,66.0,None,2026-07-08 18:42:58.447521
165,POR_Cadent_Y2026_W25,POR,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2026,Week,25,68.0,None,2026-07-08 18:42:58.447521
166,POR_Cadent_Y2026_W26,POR,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2026,Week,26,70.0,None,2026-07-08 18:42:58.447521
167,POR_Cadent_Y2026_W27,POR,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2026,Week,27,73.0,None,2026-07-08 18:42:58.447521
168,POR_Cadent_Y2026_W28,POR,BD4D080B-1D12-D329-ABD0-39FEB9804E98,None,2026,Week,28,74.0,None,2026-07-08 18:42:58.447521