In [1]:
%load_ext autoreload
%autoreload 2
%reset -f

In [2]:
from pathlib import Path
import os
import sys

# Find KPIHub root (directory containing lib/tables), then import lib.* as a package.
_here = Path.cwd().resolve()
_root = next((p for p in [_here, *list(_here.parents)[:12]] if (p / "lib" / "tables").is_dir()), None)
if _root is None:
    raise FileNotFoundError(
        f"Could not find KPIHub root (folder containing lib/tables). cwd={Path.cwd()!r}"
    )
sys.path.insert(0, str(_root))
os.chdir(_root)

from locallib.picarrodb import *
from locallib.query import *

from lib.tables.IngesterTables import *
from lib.handlers.CustomerHandler import *
from lib.config import *
from lib.KPIHubConnection import *

EU1_Conn created successfully
EU2_Conn created successfully
DataHub_Conn created successfully
US_Conn created successfully
EU1_PROD_Conn created successfully
EU2_PROD_Conn created successfully

In [3]:
import pandas as pd
customer_info_path = "CustomerInfo.csv"
customer_info_df = pd.read_csv(customer_info_path)

In [4]:
for _, customer in customer_info_df.iterrows():
    print(customer['CustomerName'])
    KPI_Customer.query_table({'db_path': DB_PATH})
    add_customer(customer['CustomerName'], CONN_DICT[customer['DBLocation']], active = customer['IsActive'])
    print('Customer added')
    KPI_Customer.query_table({'db_path': DB_PATH})
    add_customer_utilization(
        customer['CustomerName'],
        customer['WorkingHours'],
        customer['WorkingDays'],
        customer['BaseSurveyors'],

    )
    print('Utilization added')
    KPI_Utilization.query_table({'db_path': DB_PATH})
    current_year = datetime.now().year
    default_por_start_date = f'01-01-{current_year}'
    default_por_end_date = f'31-12-{current_year}'
    add_por(
        customer_name = customer['CustomerName'],
        year = 2026,
        value = customer['POR'] if pd.notna(customer['POR']) else 0,
        StartingDate = customer['PORStartingDate'] if pd.notna(customer['PORStartingDate']) else default_por_start_date,
        EndingDate = customer['POREndingDate'] if pd.notna(customer['POREndingDate']) else default_por_end_date,
        Description = ''
   
    )
    print('POR added')

    KPI_POR.query_table({'db_path': DB_PATH})
    add_output_excel_location(customer['CustomerName'], customer['OutputExcelFolder'], KPIHub_Conn)
    KPI_OutputExcelLocation.query_table({'db_path': DB_PATH}) 
    print('Output Excel Location added')

Avacon
Customer added
Utilization added
POR added
Output Excel Location added
Westnetz
Customer added
Utilization added
POR added
Output Excel Location added
Syna
Customer added
Utilization added
POR added
Output Excel Location added
NBB
Customer added
Utilization added
POR added
Output Excel Location added
EWE
Customer added
Utilization added
POR added
Output Excel Location added
ENBW
Customer added
Utilization added
POR added
Output Excel Location added
Thuega Energienetze
Customer added
Utilization added
POR added
Output Excel Location added
Energieversorgung Filstal
Customer added
Utilization added
POR added
Output Excel Location added
E-NETZ SUDHESSEN
Customer added
Utilization added
POR added
Output Excel Location added
Netz Niederösterreich
Customer added
Utilization added
POR added
Output Excel Location added
Stedin
Customer added
Utilization added
POR added
Output Excel Location added
Gas Networks Ireland
Customer added
Utilization added
POR added
Output Excel Location added
Wales and West Utilities
Customer added
Utilization added
POR added
Output Excel Location added
Cadent
Customer added
Utilization added
POR added
Output Excel Location added
PSG
Customer added
Utilization added
POR added
Output Excel Location added

In [5]:
KPI_Customer.query_table({'db_path': DB_PATH})

,CustomerId,Name,ShortName,Active,DBLocation,Country,LastUpdated
0,ED346655-AAF7-B2E7-43E2-3A10E455E700,Avacon,Avacon,1,EU1,None,2026-08-18 07:48:35.602012
1,C6565AAF-5251-1DBE-8D39-3A1F45B580A9,Westnetz,Westnetz,1,EU1,None,2026-08-18 07:48:35.652151
2,93A15FC7-DCB8-4BE9-1224-3A1F698B9C1F,Syna,Syna,1,EU1,None,2026-08-18 07:48:35.694690
3,A1E8BEC0-6A89-9454-137B-3A0A41825A09,NBB,NBB,1,EU1,None,2026-08-18 07:48:35.731597
4,7D9E66E1-6EE8-27D6-76B4-3A10E451DD30,EWE,EWE,1,EU1,None,2026-08-18 07:48:35.775467
5,8AABFD1C-862E-CF1E-5545-3A0EF16CBB61,ENBW,ENBW,1,EU1,None,2026-08-18 07:48:35.819230
6,B39ACD5B-3AB6-42D2-78D5-3A10F69CAA68,Thuega Energienetze,ThuegaEnergienetze,1,EU1,None,2026-08-18 07:48:35.865425
7,5DDE747E-0AAD-B45F-8039-3A1897DBC43F,Energieversorgung Filstal,EnergieversorgungFilstal,1,EU1,None,2026-08-18 07:48:35.913619
8,E5F6C480-6796-9A6E-79DE-3A0EF1744B1C,E-NETZ SUDHESSEN,E-NETZSUDHESSEN,1,EU1,None,2026-08-18 07:48:35.955104
9,7460AB4D-648E-297D-6073-3A145CB49DBC,Netz Niederösterreich,NetzNiederösterreich,1,EU1,None,2026-08-18 07:48:36.009138
10,FBBE8BA6-DF46-EF84-CE4D-3A20E60CED9D,Stedin,Stedin,1,EU1,None,2026-08-18 07:48:36.073206
11,B15EED6C-3E86-302A-357F-3A182BA15005,Gas Networks Ireland,GasNetworksIreland,1,EU1,None,2026-08-18 07:48:36.131735
12,027114F8-DDB7-C0D0-1398-3A173A08C9BE,Wales and West Utilities,WalesandWestUtilities,1,EU1,None,2026-08-18 07:48:36.183778
13,BD4D080B-1D12-D329-ABD0-39FEB9804E98,Cadent,Cadent,0,EU2,None,2026-08-18 07:48:36.299131
14,6F02AEAD-3145-28B1-F3EA-3A138A78230C,PSG,PSG,1,EU1,None,2026-08-18 07:48:36.344797

In [6]:
KPI_POR.query_table({'db_path': DB_PATH})

,CustomerId,Year,StartingDate,EndingDate,Description,Value,Unit,LastUpdated
0,ED346655-AAF7-B2E7-43E2-3A10E455E700,2026,2026-01-01 00:00:00,2026-12-31 00:00:00,,0.0,Km,2026-08-18 07:48:35.624858
1,C6565AAF-5251-1DBE-8D39-3A1F45B580A9,2026,2026-01-01 00:00:00,2026-12-31 00:00:00,,0.0,Km,2026-08-18 07:48:35.668698
2,93A15FC7-DCB8-4BE9-1224-3A1F698B9C1F,2026,2026-01-01 00:00:00,2026-12-31 00:00:00,,0.0,Km,2026-08-18 07:48:35.710490
3,A1E8BEC0-6A89-9454-137B-3A0A41825A09,2026,2026-01-01 00:00:00,2026-12-31 00:00:00,,0.0,Km,2026-08-18 07:48:35.750821
4,7D9E66E1-6EE8-27D6-76B4-3A10E451DD30,2026,2026-01-01 00:00:00,2026-12-31 00:00:00,,0.0,Km,2026-08-18 07:48:35.795397
5,8AABFD1C-862E-CF1E-5545-3A0EF16CBB61,2026,2026-01-01 00:00:00,2026-12-31 00:00:00,,0.0,Km,2026-08-18 07:48:35.838427
6,B39ACD5B-3AB6-42D2-78D5-3A10F69CAA68,2026,2026-01-01 00:00:00,2026-12-31 00:00:00,,0.0,Km,2026-08-18 07:48:35.883607
7,5DDE747E-0AAD-B45F-8039-3A1897DBC43F,2026,2026-01-01 00:00:00,2026-12-31 00:00:00,,0.0,Km,2026-08-18 07:48:35.929116
8,E5F6C480-6796-9A6E-79DE-3A0EF1744B1C,2026,2026-01-01 00:00:00,2026-12-31 00:00:00,,0.0,Km,2026-08-18 07:48:35.975263
9,7460AB4D-648E-297D-6073-3A145CB49DBC,2026,2026-01-01 00:00:00,2026-12-31 00:00:00,,0.0,Km,2026-08-18 07:48:36.033855
10,FBBE8BA6-DF46-EF84-CE4D-3A20E60CED9D,2026,2026-01-01 00:00:00,2026-12-31 00:00:00,,0.0,Km,2026-08-18 07:48:36.099404
11,B15EED6C-3E86-302A-357F-3A182BA15005,2026,2026-04-01 00:00:00,2027-03-31 00:00:00,,0.0,Km,2026-08-18 07:48:36.154157
12,027114F8-DDB7-C0D0-1398-3A173A08C9BE,2026,2026-04-01 00:00:00,2027-03-31 00:00:00,,0.0,Km,2026-08-18 07:48:36.202954
13,BD4D080B-1D12-D329-ABD0-39FEB9804E98,2026,2026-04-01 00:00:00,2027-03-31 00:00:00,,127000.0,Km,2026-08-18 07:48:36.318205
14,6F02AEAD-3145-28B1-F3EA-3A138A78230C,2026,2026-04-01 00:00:00,2026-12-31 00:00:00,,5300.0,Km,2026-08-18 07:48:36.364380

In [7]:
KPI_Utilization.query_table({'db_path': DB_PATH})

,CustomerId,WorkingDays,WorkingHours,SunriseHour,SunsetHour,BaseSurveyorCount,Description,LastUpdated
0,ED346655-AAF7-B2E7-43E2-3A10E455E700,5,6,None,None,NaN,None,2026-08-18 07:48:35.614999
1,C6565AAF-5251-1DBE-8D39-3A1F45B580A9,5,6,None,None,NaN,None,2026-08-18 07:48:35.660007
2,93A15FC7-DCB8-4BE9-1224-3A1F698B9C1F,5,6,None,None,NaN,None,2026-08-18 07:48:35.702255
3,A1E8BEC0-6A89-9454-137B-3A0A41825A09,5,6,None,None,NaN,None,2026-08-18 07:48:35.740460
4,7D9E66E1-6EE8-27D6-76B4-3A10E451DD30,5,6,None,None,NaN,None,2026-08-18 07:48:35.784604
5,8AABFD1C-862E-CF1E-5545-3A0EF16CBB61,5,6,None,None,NaN,None,2026-08-18 07:48:35.829368
6,B39ACD5B-3AB6-42D2-78D5-3A10F69CAA68,5,6,None,None,NaN,None,2026-08-18 07:48:35.874923
7,5DDE747E-0AAD-B45F-8039-3A1897DBC43F,5,6,None,None,NaN,None,2026-08-18 07:48:35.920961
8,E5F6C480-6796-9A6E-79DE-3A0EF1744B1C,5,6,None,None,NaN,None,2026-08-18 07:48:35.963762
9,7460AB4D-648E-297D-6073-3A145CB49DBC,5,6,None,None,NaN,None,2026-08-18 07:48:36.021139
10,FBBE8BA6-DF46-EF84-CE4D-3A20E60CED9D,5,6,None,None,NaN,None,2026-08-18 07:48:36.082963
11,B15EED6C-3E86-302A-357F-3A182BA15005,6,8,None,None,NaN,None,2026-08-18 07:48:36.144017
12,027114F8-DDB7-C0D0-1398-3A173A08C9BE,5,8,None,None,NaN,None,2026-08-18 07:48:36.194052
13,BD4D080B-1D12-D329-ABD0-39FEB9804E98,7,7,None,None,25.0,None,2026-08-18 07:48:36.308594
14,6F02AEAD-3145-28B1-F3EA-3A138A78230C,5,8,None,None,NaN,None,2026-08-18 07:48:36.355140