In [12]:
%load_ext autoreload
%autoreload 2
%reset -f

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [13]:
from pathlib import Path
import os
from os.path import join
import sys

# Find KPIHub root (directory containing lib/tables), then import lib.* as a package.
_here = Path.cwd().resolve()
_root = next((p for p in [_here, *list(_here.parents)[:12]] if (p / "lib" / "tables").is_dir()), None)
if _root is None:
    raise FileNotFoundError(
        f"Could not find KPIHub root (folder containing lib/tables). cwd={Path.cwd()!r}"
    )
sys.path.insert(0, str(_root))
os.chdir(_root)

from locallib.picarrodb import *
from locallib.slack import *
from locallib.etl import Loggers
from locallib.pandas import *
from locallib.box import *

from lib.tables.IngesterTables import *
from lib.handlers.CustomerHandler import *
from lib.config import *
from lib.KPIHubConnection import *
from lib.query.bank import *

from datetime import date
from datetime import timedelta

In [14]:
Query(query = "SELECT * FROM KPI_ReportSummary").execute(KPIHub_Conn)

,ReportId,CustomerId,ReportName,ReportDate,ReportYear,ReportMonth,ReportWeek,ReportAssetLengthKm,AssetCoveredLengthKm,DistributionPipeKm,...,ServicePipeCoveredKm,BoundaryName,BoundaryType,BoundaryMode,BoundaryPlant,BoundarySubplant,BoundaryRegion,BoundarySubRegion,ReportArea,LastUpdated
0,FC5086EC-A25D-56E2-6211-3A20EF847249,C6565AAF-5251-1DBE-8D39-3A1F45B580A9,CR-FC5086,2026-04-30 07:43:19.113000,2026,4,18,26.655462,26.420200,18.221517,...,8.215250,B26R1 - RZ Westliches Rheinland - Bedburg #01,Boundaries 2026 R1,customer boundary,RZ_Westliches_Rheinland,Bedburg,None,None,MULTIPOLYGON (((6.51979027138305 50.9853218794...,2026-07-21 17:42:38.053428
1,AA0B65B3-5DCD-28EE-E5C5-3A20EF8577AA,C6565AAF-5251-1DBE-8D39-3A1F45B580A9,CR-AA0B65,2026-04-30 07:44:26.027000,2026,4,18,53.955638,52.021254,34.769079,...,18.283261,B26R1 - RZ Westliches Rheinland - Bedburg #02,Boundaries 2026 R1,customer boundary,RZ_Westliches_Rheinland,Bedburg,None,None,MULTIPOLYGON (((6.5722543011448362 51.01104276...,2026-07-21 17:42:38.053428
2,672697F0-3652-A300-3D21-3A2103EAF2BE,C6565AAF-5251-1DBE-8D39-3A1F45B580A9,CR-672697,2026-05-04 06:47:40.990000,2026,5,19,51.554193,49.612014,30.757502,...,20.238462,B26R1 - RZ Oestliches Ruhrgebiet - Selm #01,Boundaries 2026 R1,customer boundary,RZOestliches_Ruhrgebiet,Selm,None,None,MULTIPOLYGON (((7.4814644413462759 51.69713274...,2026-07-21 17:42:38.053428
3,77C2F227-6AE4-2CC8-35E1-3A2103F70BA5,C6565AAF-5251-1DBE-8D39-3A1F45B580A9,CR-77C2F2,2026-05-04 07:00:53.797000,2026,5,19,16.357955,15.766509,11.572134,...,4.750237,B26R1 - RZ Westliches Rheinland - Bedburg #03,Boundaries 2026 R1,customer boundary,RZ_Westliches_Rheinland,Bedburg,None,None,MULTIPOLYGON (((6.57099443715362 50.9916996772...,2026-07-21 17:42:38.053428
4,9911EDD4-10E4-88DC-CCA4-3A21091BF3C8,C6565AAF-5251-1DBE-8D39-3A1F45B580A9,CR-9911ED,2026-05-05 06:59:18.600000,2026,5,19,35.841708,35.782984,23.391438,...,12.412397,B26R1 - RZ Westliches Rheinland - Bedburg #04,Boundaries 2026 R1,customer boundary,RZ_Westliches_Rheinland,Bedburg,None,None,MULTIPOLYGON (((6.56175888442257 50.9890694473...,2026-07-21 17:42:38.053428
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8902,9F297B8A-C914-59B8-2F5A-3A227DFD8DEC,CFFB9000-94BD-BA72-B352-39EBA962116D,CR-9F297B,2026-07-16 16:44:28.013000,2026,7,29,13.217780,11.539397,13.217780,...,NaN,B26 - 2IRG I800441 IMPIANTO ACQUAPPESA,2iRG 2026,customer boundary,800441,2IRG,Calabria,CO43,MULTIPOLYGON (((15.949830144790445 39.49729583...,2026-07-21 17:43:04.325660
8903,02EB1936-01B1-ED8E-C25C-3A2291EE343B,CFFB9000-94BD-BA72-B352-39EBA962116D,CR-02EB19,2026-07-20 13:40:06.330000,2026,7,30,113.615587,110.099367,113.615587,...,NaN,B26 - I275 M10 ROMA MUNICIPIO 10 #3,Italgas 2026,customer boundary,275,ITG,Roma-Sud,CO75,MULTIPOLYGON (((12.32387465237878 41.768400712...,2026-07-21 17:43:04.325660
8904,46B20EEE-814B-94E3-92AE-3A22926DA2EC,CFFB9000-94BD-BA72-B352-39EBA962116D,CR-46B20E,2026-07-20 15:59:17.740000,2026,7,30,21.226626,20.360021,21.226626,...,NaN,B26 - 2IRG I800373 C60018 CASALVIERI,2iRG 2026,customer boundary,800373,2IRG,Lazio Sud,CO26,MULTIPOLYGON (((13.726811533334386 41.65363296...,2026-07-21 17:43:04.325660
8905,38639780-15E8-1BFD-E202-3A2295C71C06,CFFB9000-94BD-BA72-B352-39EBA962116D,CR-386397,2026-07-21 07:35:53.093000,2026,7,30,42.221932,40.521629,42.221932,...,NaN,B26 - I76 C110001 ANDRIA #2 / C110009 TRANI,Italgas 2026,customer boundary,76,ITG,Puglia Nord - Molise,CO85,MULTIPOLYGON (((16.339079402479552 41.25403217...,2026-07-21 17:43:04.325660
8906,2CDB8775-3883-8F93-C6ED-3A2295EB938C,CFFB9000-94BD-BA72-B352-39EBA962116D,CR-2CDB87,2026-07-21 08:15:42.990000,2026,7,30,13.320862,13.152267,13.320862,...,NaN,B26 - 2IRG I800373 C60015 BROCCOSTELLA / C6007...,2iRG 2026,customer boundary,800373,2IRG,Lazio Sud,CO26,MULTIPOLYGON (((13.657876978726712 41.69756258...,2026-07-21 17:43:04.325660

In [15]:
Query(query = "SELECT * FROM KPI_PeakAboveSAT").execute(KPIHub_Conn)

Empty DataFrame
Columns: [CustomerId, PeakName, PeakId, Date, ReportYear, WeekNumber, Disposition, LocalTime, BoundaryName, BoundaryRegion, EmissionRate, PeakGpsLatitude, PeakGpsLongitude, Easting, Northing, UserName, SurveyorUnit, AnalyzerSerialNumber, Hyperlink, LastUpdated]
Index: []

In [16]:
Query(query = 'SELECT * FROM KPI_Customer').execute(KPIHub_Conn)

,CustomerId,Name,ShortName,DBLocation,LastUpdated
0,C6565AAF-5251-1DBE-8D39-3A1F45B580A9,Westnetz,Westnetz,EU1,2026-07-21 17:20:14.914452
1,CFFB9000-94BD-BA72-B352-39EBA962116D,ITALGAS,ITALGAS,EU2,2026-07-21 17:48:25.536208

In [17]:
Query(query = "SELECT * FROM KPI_OutputExcelLocation").execute(KPIHub_Conn)

,CustomerId,BoxFolderId,LastUpdated
0,C6565AAF-5251-1DBE-8D39-3A1F45B580A9,398249270000,2026-07-21 17:20:14.920128
1,CFFB9000-94BD-BA72-B352-39EBA962116D,401896871043,2026-07-21 17:48:25.547253

In [18]:
Query(query = "SELECT * FROM KPI_Definition").execute(KPIHub_Conn)

,Name,Unit,Formula,Description,LastUpdated
0,PeriodValue,,,Number of the week starting from 1st of Jan,2026-07-21 17:48:25.556561
1,ReportAssetLengthKm,Km,,Total length of all the assets in the specifie...,2026-07-21 17:48:25.556567
2,AssetCoveredLengthKm,Km,,Total length of all the assets covered in the ...,2026-07-21 17:48:25.556568
3,CumulativeAssetCoveredLengthKm,Km,,Cumulative covered length of all the assets co...,2026-07-21 17:48:25.556568
4,DistributionPipeKm,Km,,Total length of all the mains in the report,2026-07-21 17:48:25.556569
5,DistributionPipeCoveredKm,Km,,Total length of all the mains covered in the r...,2026-07-21 17:48:25.556570
6,ServicePipeKm,Km,,Total length of all the services in the report,2026-07-21 17:48:25.556571
7,ServicePipeCoveredKm,Km,,Total length of all the services covered in th...,2026-07-21 17:48:25.556572
8,ReportCount,Report,,Total number of reports in the specified week,2026-07-21 17:48:25.556573
9,DaysCount,Day,,Total number of days worked in the specified week,2026-07-21 17:48:25.556574
10,FOVMain,Percent,DistributionPipeCoveredKm / DistributionPipeKm,Km of mains covered over the total Km of mains,2026-07-21 17:48:25.556575
11,SurveyDurationHours,Hours,,Total hours driven by all cars in the week,2026-07-21 17:48:25.556576
12,TargetDurationHours,Hours,,Exepected total number hours driven by all car...,2026-07-21 17:48:25.556577
13,CustomerUtilization,Percent,SurveyDurationHours / TargetDurationHours,Total hours driven by all cars in the week ove...,2026-07-21 17:48:25.556578
14,StarndardUtilization,Percent,SurveyDurationHours / TargetDurationHours,Total hours driven by all cars in the week ove...,2026-07-21 17:48:25.556579
15,TotalSurveyors,Surveyor,,Total number of surveyors in the specified week,2026-07-21 17:48:25.556580
16,ProductivityPerSurveyor,Km / Surveyor,DistributionPipeCoveredKm / TotalSurveyors,Total length of all the assets covered in the ...,2026-07-21 17:48:25.556581
17,SurveyCount,Survey,,Total number of surveys in the specified week,2026-07-21 17:48:25.556582
18,AvgSpeedKm,Km/h,,Average speed counting all the cars in the spe...,2026-07-21 17:48:25.556582
19,SurveysCarDay,Survey / Car / Day,SurveyCount / TotalSurveyors / DaysCount,Total number of surveys per car per day in the...,2026-07-21 17:48:25.556583
20,IdleTime,Percent,IdleTimeMinutes / SurveyDurationMinutes,Ratio of idle time over the total survey duration,2026-07-21 17:48:25.556584
21,TotalDrivenLengthKm,Km,,Total length driven in the specified week,2026-07-21 17:48:25.556585
22,DrivingRatio,Ratio,TotalKilometers / DistributionPipeCoveredKm,Total length driven in the specified week over...,2026-07-21 17:48:25.556586
23,NightDrivenLength,Km,,Total length covered during the night in the s...,2026-07-21 17:48:25.556587
24,DayDrivenLength,Km,,Total length covered during the day in the spe...,2026-07-21 17:48:25.556588
25,NightRatio,Percent,,NightKm / TotalKilometers,2026-07-21 17:48:25.556589
26,DayRatio,Percent,,DayKm / TotalKilometers,2026-07-21 17:48:25.556590
27,PeakAboveSATCount,Peak,,Total number of peaks above SAT in the specifi...,2026-07-21 17:48:25.556591
28,LisaCount,Lisa,,"Total number of Lisa in the specified week, (N...",2026-07-21 17:48:25.556592
29,EmissionRate,SCFH,,"Total emission rate in the specified week, (No...",2026-07-21 17:48:25.556593
30,B0Count,Lisa,,"Total number of B0 in the specified week, (No ...",2026-07-21 17:48:25.556594
31,B1Count,Lisa,,"Total number of B1 in the specified week, (No ...",2026-07-21 17:48:25.556595
32,Bm1Count,Lisa,,"Total number of B-1 in the specified week, (No...",2026-07-21 17:48:25.556596
33,Bm2Count,Lisa,,"Total number of B-2 in the specified week, (No...",2026-07-21 17:48:25.556598
34,NGCount,Lisa,,"Total number of NG in the specified week, (Wit...",2026-07-21 17:48:25.556599
35,PGCount,Lisa,,"Total number of PG in the specified week, (Wit...",2026-07-21 17:48:25.556600
36,Not_NGCount,Lisa,,"Total number of Not NG in the specified week, ...",2026-07-21 17:48:25.556601
37,LisaDensity,Lisa / Km,LisaCount / DistributionPipeCoveredKm,Number of Lisa per Km of Asset Covered,2026-07-21 17:48:25.556602
38,InstatanoeusEmission,SCFH / Km,EmissionRate / DistributionPipeCoveredKm,Emission rate per Km of Asset Covered,2026-07-21 17:48:25.556603
39,B0Density,Lisa / Km,B0Count / DistributionPipeCoveredKm,Number of B0 per Km of Asset Covered,2026-07-21 17:48:25.556603
40,B1Density,Lisa / Km,B1Count / DistributionPipeCoveredKm,Number of B1 per Km of Asset Covered,2026-07-21 17:48:25.556604
41,Bm1Density,Lisa / Km,Bm1Count / DistributionPipeCoveredKm,Number of B-1 per Km of Asset Covered,2026-07-21 17:48:25.556605
42,Bm2Density,Lisa / Km,Bm2Count / DistributionPipeCoveredKm,Number of B-2 per Km of Asset Covered,2026-07-21 17:48:25.556606
43,B0Share,Percent,B0Count / LisaCount,Number of B0 per Lisa,2026-07-21 17:48:25.556607
44,B1Share,Percent,B1Count / LisaCount,Number of B1 per Lisa,2026-07-21 17:48:25.556608
45,Bm1Share,Percent,Bm1Count / LisaCount,Number of B-1 per Lisa,2026-07-21 17:48:25.556609
46,Bm2Share,Percent,Bm2Count / LisaCount,Number of B-2 per Lisa,2026-07-21 17:48:25.556610
47,NGShare,Percent,NGCount / (NGCount + Not_NGCount + PGCount),Number of NG per Lisa,2026-07-21 17:48:25.556611
48,PGShare,Percent,PGCount / (NGCount + Not_NGCount + PGCount),Number of PG per Lisa,2026-07-21 17:48:25.556612
49,Not_NGShare,Percent,Not_NGCount / (NGCount + Not_NGCount + PGCount),Number of Not NG per Lisa,2026-07-21 17:48:25.556613
50,POR,Km,,Total Km of the POR in the year,2026-07-21 17:48:25.556614
51,CurrentCompletion,Percent,CumulativeAssetCoveredLengthKm / POR,Current completion of the network based on the...,2026-07-21 17:48:25.556614

In [19]:
Query(query = "SELECT DISTINCT KPIId FROM KPI_Data").execute(KPIHub_Conn)

                             KPIId
0                          FOVMain
1              ReportAssetLengthKm
2             AssetCoveredLengthKm
3               DistributionPipeKm
4        DistributionPipeCoveredKm
5                    ServicePipeKm
6             ServicePipeCoveredKm
7                      ReportCount
8                        LisaCount
9                     EmissionRate
10                         B0Count
11                         B1Count
12                        Bm1Count
13                        Bm2Count
14                         NGCount
15                         PGCount
16                     Not_NGCount
17                     LisaDensity
18            InstatanoeusEmission
19                       B0Density
20                       B1Density
21                      Bm1Density
22                      Bm2Density
23                       NGDensity
24                       PGDensity
25                         B0Share
26                         B1Share
27                        Bm1Share
28                        Bm2Share
29                         NGShare
30                         PGShare
31                     Not_NGShare
32             SurveyDurationHours
33             TargetDurationHours
34             CustomerUtilization
35            StarndardUtilization
36                  TotalSurveyors
37         ProductivityPerSurveyor
38                     SurveyCount
39                      AvgSpeedKm
40                   SurveysCarDay
41                        IdleTime
42                       DaysCount
43             TotalDrivenLengthKm
44                    DrivingRatio
45               NightDrivenLength
46                 DayDrivenLength
47                      NightRatio
48                        DayRatio
49  CumulativeAssetCoveredLengthKm
50                             POR
51               CurrentCompletion

In [20]:
Query(query = "SELECT * FROM KPI_POR").execute(KPIHub_Conn)

,CustomerId,Year,StartingDate,EndingDate,Description,Value,Unit,LastUpdated
0,C6565AAF-5251-1DBE-8D39-3A1F45B580A9,2026,2026-01-01 00:00:00,2026-12-31 00:00:00,,0.0,Km,2026-07-21 17:20:14.926370
1,CFFB9000-94BD-BA72-B352-39EBA962116D,2026,2026-01-01 00:00:00,2026-12-31 00:00:00,,0.0,Km,2026-07-21 17:48:25.552915

In [21]:
Query(query = "SELECT * FROM KPI_Utilization").execute(KPIHub_Conn)

,CustomerId,WorkingDays,WorkingHours,BaseSurveyorCount,Description,LastUpdated
0,C6565AAF-5251-1DBE-8D39-3A1F45B580A9,5,6,2,None,2026-07-21 17:20:14.931326
1,CFFB9000-94BD-BA72-B352-39EBA962116D,5,6,2,None,2026-07-21 17:48:25.542517

In [25]:
Query(query = "SELECT * FROM KPI_Data WHERE PeriodType = 'Year'").execute(KPIHub_Conn)

,Id,KPIId,CustomerId,BoundaryRegion,Year,PeriodType,PeriodValue,Value,DataType,LastUpdated
0,FOVMain_ITALGAS_Y2023_BAbruzzo,FOVMain,CFFB9000-94BD-BA72-B352-39EBA962116D,Abruzzo,2023,Year,None,None,None,2026-07-21 18:43:36.599469
1,FOVMain_ITALGAS_Y2023_BCalabria,FOVMain,CFFB9000-94BD-BA72-B352-39EBA962116D,Calabria,2023,Year,None,None,None,2026-07-21 18:43:36.599469
2,FOVMain_ITALGAS_Y2023_BCampania,FOVMain,CFFB9000-94BD-BA72-B352-39EBA962116D,Campania,2023,Year,None,None,None,2026-07-21 18:43:36.599469
3,FOVMain_ITALGAS_Y2023_BCentroItalia,FOVMain,CFFB9000-94BD-BA72-B352-39EBA962116D,Centro Italia,2023,Year,None,None,None,2026-07-21 18:43:36.599469
4,FOVMain_ITALGAS_Y2023_BLazioSud,FOVMain,CFFB9000-94BD-BA72-B352-39EBA962116D,Lazio Sud,2023,Year,None,None,None,2026-07-21 18:43:36.599469
...,...,...,...,...,...,...,...,...,...,...
2939,Not_NGShare_ITALGAS_Y2026_BSiciliaEst,Not_NGShare,CFFB9000-94BD-BA72-B352-39EBA962116D,Sicilia Est,2026,Year,None,17.7,None,2026-07-21 18:43:37.168440
2940,Not_NGShare_ITALGAS_Y2026_BSiciliaOvest,Not_NGShare,CFFB9000-94BD-BA72-B352-39EBA962116D,Sicilia Ovest,2026,Year,None,37.26,None,2026-07-21 18:43:37.168440
2941,Not_NGShare_ITALGAS_Y2026_BTorino,Not_NGShare,CFFB9000-94BD-BA72-B352-39EBA962116D,Torino,2026,Year,None,22.79,None,2026-07-21 18:43:37.168440
2942,Not_NGShare_ITALGAS_Y2026_BVenetoNord-Friuli,Not_NGShare,CFFB9000-94BD-BA72-B352-39EBA962116D,Veneto Nord - Friuli,2026,Year,None,24.45,None,2026-07-21 18:43:37.168440
2943,Not_NGShare_ITALGAS_Y2026_BVenetoSud,Not_NGShare,CFFB9000-94BD-BA72-B352-39EBA962116D,Veneto Sud,2026,Year,None,26.14,None,2026-07-21 18:43:37.168440